/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#40465c",
        "on-tertiary-fixed": "#241a00",
        "secondary-fixed": "#dce1fd",
        "tertiary-fixed-dim": "#e6c364",
        "outline": "rgb(var(--color-outline) / <alpha-value>)",
        "primary-container": "rgb(var(--color-primary-container) / <alpha-value>)",
        "on-secondary": "#ffffff",
        "outline-variant": "rgb(var(--color-outline-variant) / <alpha-value>)",
        "on-primary-fixed": "#03174b",
        "inverse-surface": "#2a313d",
        "on-secondary-container": "#5e637b",
        "surface-variant": "rgb(var(--color-surface-variant) / <alpha-value>)",
        "background": "rgb(var(--color-background) / <alpha-value>)",
        "error": "#ba1a1a",
        "on-tertiary-container": "#b19238",
        "on-error": "#ffffff",
        "inverse-primary": "#b5c4ff",
        "on-surface": "rgb(var(--color-on-surface) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--color-surface-container-lowest) / <alpha-value>)",
        "surface-tint": "#4c5c92",
        "secondary-container": "#dce1fd",
        "error-container": "#ffdad6",
        "on-surface-variant": "rgb(var(--color-on-surface-variant) / <alpha-value>)",
        "primary": "rgb(var(--color-primary) / <alpha-value>)",
        "surface-dim": "rgb(var(--color-surface-dim) / <alpha-value>)",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#c0c5e0",
        "on-primary": "rgb(var(--color-on-primary) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--color-surface-container-highest) / <alpha-value>)",
        "inverse-on-surface": "#ebf1ff",
        "surface-container-high": "rgb(var(--color-surface-container-high) / <alpha-value>)",
        "surface": "rgb(var(--color-surface) / <alpha-value>)",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#584400",
        "primary-fixed": "#dce1ff",
        "tertiary-container": "#3a2c00",
        "tertiary": "#221800",
        "on-primary-fixed-variant": "#344478",
        "on-primary-container": "rgb(var(--color-on-primary-container) / <alpha-value>)",
        "on-secondary-fixed": "#151b2e",
        "secondary": "#585d74",
        "on-background": "rgb(var(--color-on-surface) / <alpha-value>)",
        "surface-container-low": "rgb(var(--color-surface-container-low) / <alpha-value>)",
        "surface-container": "rgb(var(--color-surface-container) / <alpha-value>)",
        "surface-bright": "rgb(var(--color-background) / <alpha-value>)",
        "primary-fixed-dim": "#b5c4ff",
        "tertiary-fixed": "#ffe08f"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
